services:
  musiclab-backend:
    build: ./backend
    container_name: musiclab-backend
    ports:
      - "8091:8091"
    volumes:
      - /volume1/DS420/Musik:/music
      - /volume1/docker/musiclab/data:/data
      - /volume1/docker/musiclab/backend/app:/app/app
    environment:
      - MUSIC_ROOT=/music
      - DB_PATH=/data/musiclab.sqlite
    restart: unless-stopped

  musiclab-frontend:
    build: ./frontend
    container_name: musiclab-frontend
    ports:
      - "8092:80"
    volumes:
      - /volume1/docker/musiclab/frontend:/usr/share/nginx/html:ro
    depends_on:
      - musiclab-backend
    restart: unless-stopped
